version: '3.8'
services:
  mongo:
    image: mongo
    command:  ["mongod", "--replSet", "rs0", "--auth", "--keyFile", "/etc/mongo/mongodb-keyfile"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./init-mongo:/docker-entrypoint-initdb.d
       

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./init-postgres:/docker-entrypoint-initdb.d

  app:
    build: ./nodejs-app
    depends_on:
      - mongo
      - postgres
    environment:
      MONGO_URL: mongodb://${MONGODB_ROOT_USER}:${MONGODB_ROOT_PASSWORD}@mongo:27017/
      MONGO_DB: ${MONGODB_DB}
      POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
